### ISSUE TITLE
error when starting

### ISSUE THREAD

**Issue by mandar1jn** [RealTheSunCat/Whitehole-1.4#10]
I tried opening whitehole, but it didn't work. I tried starting it trough the command java -jar whitehole.jar. I got the same error. I downloaded the latest version, but had the same result.

The error:
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at com.thesuncat.whitehole.smg.GameArchive.getGalaxies(GameArchive.java:63)
        at com.thesuncat.whitehole.swing.MainFrame.openGameDir(MainFrame.java:154)
        at com.thesuncat.whitehole.swing.MainFrame.<init>(MainFrame.java:135)
        at com.thesuncat.whitehole.Whitehole.main(Whitehole.java:129)

**Comment by TheSunCat** [comment]
Should be "fixed" by 64fa14493695c281007e4fc3087d15b8f87da501, but it looks like this error would trigger if your StageData directory is empty. Are you sure you're opening a game filesystem with a populated StageData?
